langi/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .forms import EmailValidationOnForgotPassword, PasswordValidationOnForgotPassword

from . import views

app_name = 'accounts'

urlpatterns = [
    # path('', views.test, name='home'),
    path('signup/', views.signUpPage, name='signup'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('tc/', views.termsPage, name='terms'),
    path('privacy/', views.privacyPage, name='privacy'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html', success_url=reverse_lazy('accounts:password_reset_done'), form_class=EmailValidationOnForgotPassword), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete'), form_class=PasswordValidationOnForgotPassword), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
]

langi/langi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('api/', include('langiAPI.urls')),
    path('', include('accounts.urls')),
    path('', include('mainContent.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

langi/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    language = models.CharField(max_length=30)
    agreement = models.BooleanField(default=False)
    darkMode = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

langi/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, required=True, help_text='Required. Inform a valid email address.', )
    language = forms.CharField()
    agreement = forms.BooleanField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'language', 'agreement']

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user_count = User.objects.filter(email=email).count()
        if user_count > 0:
            raise forms.ValidationError(_("User with this email address already exists."))
        return email

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.pop("autofocus", None)
        # add custom error messages
        self.fields['agreement'].error_messages.update({
            'required': _('You must accept the Terms & Conditions'),
        })

        self.fields['username'].error_messages.update({
            'required': _('All fields are required.'),
            'invalid': _('Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.'),
            'max_length': _('The username cannot contain more than 150 characters.'),
            'unique': _('A user with that username already exists.'),
        })
        self.fields['email'].error_messages.update({
            'required': _('All fields are required.'),
            'invalid': _('Enter a valid email address.'),
        })
        self.fields['password1'].error_messages.update({
            'required': _('All fields are required.'),
        })
        self.fields['password2'].error_messages.update({
            'required': _('All fields are required.'),
        })

        self.error_messages.update({
            'password_mismatch': _('The two password fields didn’t match.'),
        })

        self.fields['username'].help_text = _('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.')
        self.fields['password1'].help_text = _("Your password can't be too similar to your other personal information. Your password must contain at least 8 characters. Your password can't be a commonly used password. Your password can't be entirely numeric.")


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.pop("autofocus", None)
        # add custom error messages
        self.error_messages.update({
            'invalid_login': _('Please enter valid login details.'),
        })


class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            msg = _('There is no user registered with the specified email address.')
            self.add_error('email', msg)
        return email

    def __init__(self, *args, **kwargs):
        super(EmailValidationOnForgotPassword, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.pop("autofocus", None)
        # add custom error messages
        self.fields['email'].error_messages.update({
            'required': _('Please enter email address.'),
            'invalid': _('Enter a valid email address.'),
        })


class PasswordValidationOnForgotPassword(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(PasswordValidationOnForgotPassword, self).__init__(*args, **kwargs)

        self.error_messages.update({
            'password_mismatch': _('The two password fields didn’t match.'),
        })

        self.fields['new_password1'].error_messages.update({
            'required': _('All fields are required.'),
        })
        self.fields['new_password2'].error_messages.update({
            'required': _('All fields are required.'),
        })

        self.fields['new_password1'].help_text = _("Your password can't be too similar to your other personal information. Your password must contain at least 8 characters. Your password can't be a commonly used password. Your password can't be entirely numeric.")

langi/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

from .forms import SignUpForm, LoginForm
from django.utils.translation import gettext as _
from .utilitySet import getLanguageCode

LANGUAGE_QUERY_PARAMETER = 'language'


def signUpPage(request):
    if request.user.is_authenticated:
        return redirect('mainContent:home')
    else:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save()
                user.refresh_from_db()
                user.profile.language = getLanguageCode(form.cleaned_data.get('language'))
                user.profile.agreement = form.cleaned_data.get('agreement')
                user.save()
                username = form.cleaned_data.get('username')
                messages.success(request, _(f"New account was successfully created: {username}"))
                return redirect('accounts:login')
            else:
                for msg in form.error_messages:
                    messages.error(request, f"{msg}:{form.error_messages[msg]}")
        else:
            form = SignUpForm()
        context = {'form': form}
        return render(request, 'accounts/signup.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('mainContent:home')
    else:
        if request.method == 'POST':
            form = LoginForm(request, request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=raw_password)
                if user is not None:
                    login(request, user)
                    return redirect('mainContent:home')
                else:
                    messages.error(request, _("Invalid username or password."))
            else:
                messages.error(request, _("Invalid username or password."))
        else:
            form = LoginForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    messages.info(request, "Logged out successfully.")
    return redirect('accounts:login')


def termsPage(request):
    return render(request, 'accounts/terms.html')


def privacyPage(request):
    return render(request, 'accounts/privacy.html')

langi/accounts/templates/accounts/footer.html
{% load i18n %}
<footer class="footer">
    <div class="footer__sources sources">
        <p class="sources-text">{% trans "Sources" %}</p>
        <p class="sources-link">
            {% with '<a class="link-privacy" href="https://www.flaticon.com/" title="Flaticon">' as link_begin %}
            {% with "</a>" as link_end %}
            {% blocktrans %}Icons made by Freepik from
            {{ link_begin }}www.flaticon.com{{ link_end }}{% endblocktrans %}
            {% endwith %}
            {% endwith %}
        </p>
        <p class="sources-link">
            {% with '<a class="link-privacy" href="https://www.flaticon.com/" title="Flaticon">' as link_begin %}
            {% with "</a>" as link_end %}
            {% blocktrans %}Icons made by Roundicons from
            {{ link_begin }}www.flaticon.com{{ link_end }}{% endblocktrans %}
            {% endwith %}
            {% endwith %}
        </p>
    </div>
    <div class="footer__contact-info contact-info">
        <p class="contact-text">{% trans "Contact"  %}</p>
        <p class="contact-email">{% trans "email: kamilwaszewski@gmail.com" %}</p>
        <div class="social-media-icons">
            <ul class="media-list">
                <li><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                <li><a href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="https://www.youtube.com"><i class="fa fa-youtube"></i></a></li>
                <li><a href="https://www.instagram.com"><i class="fa fa-instagram"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="footer__privacy">
        <a class="link-privacy" href="{% url 'accounts:privacy' %}">{% trans "Privacy Policy"  %}</a>
        <a class="link-privacy" href="{% url 'accounts:terms' %}">{% trans " Terms &amp; Conditions" %}</a>
        <p>&copy; 2020 Langi Application</p>
    </div>
</footer>

langi/accounts/templates/accounts/layout.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        {% load sass_tags %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% sass_src 'accounts/css/accounts.scss' %}">
        <link rel="stylesheet" type="text/css" href="{% sass_src 'accounts/css/fonts.scss' %}">


        {% block css %}{% endblock %}
        <!-- Fonts -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/tonsky/FiraCode@1.207/distr/fira_code.css">
        <!--<link
            href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&family=Noto+Sans+KR:wght@100;300;400;500;700;900&family=Noto+Sans+SC:wght@100;300;400;500;700;900&family=Noto+Sans+TC:wght@100;300;400;500;700;900&display=swap"
            rel="stylesheet">-->

        <!-- Username, password icons -->
        <script src="https://kit.fontawesome.com/a81368914c.js"></script>

        <!-- Social Media Icons -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body id="main-body" onload="initializeBody('{{ LANGUAGE_CODE }}')">

        <div class="container">
            <nav class="navigation">
                <div class="logo">
                    <a href="{% url 'accounts:login' %}"><img src="{% static 'accounts/images/LogoNameDark.png' %}"
                            alt="Application logo"></a>
                </div>
            </nav>

            {% block contentTP %}
            {% endblock %}


            <div class="form-box">
                <div class="login-content">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>

            {% include 'accounts/footer.html' %}
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
        <script type="text/javascript" src="{% static 'accounts/js/main.js' %}"></script>
        {% block js %}
        {% endblock %}
    </body>

</html>

langi/accounts/templates/accounts/login.html
{% extends 'accounts/layout.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}
{% get_current_language as LANGUAGE_CODE %}

<form method="POST" action="{% url 'accounts:login' %}" novalidate>
    {% csrf_token %}
    <div class="form__welcome welcome" id="welcome">
        <img class="welcome__flagIcon" src="{% static 'accounts/images/flags/turkey.svg' %}" alt="Flag icon">
        <h1 class="welcome__title">{% trans "Welcome" %}</h1>
    </div>
    <div class="input-div uname">
        <div class="i">
            <i class="fas fa-user"></i>
        </div>
        <div class="div">
            <h5>{% trans "Username" %}</h5>
            {% render_field form.username type="text" class="input" %}
            <!--<input type="text" class="input">-->
        </div>
    </div>
    <div class="input-div pass">
        <div class="i">
            <i class="fas fa-lock"></i>
        </div>
        <div class="div">
            <h5>{% trans "Password" %}</h5>
            {% render_field form.password type="password" class="input" %}
            <!--<input type="password" class="input">-->
        </div>
    </div>
    <a class="link" href="{% url 'accounts:password_reset' %}">{% trans "Forgot Password?" %}</a>

    {% if form.errors %}
    {% for error, value in form.error_messages.items %}
    {% if error == "invalid_login" %}
    <p class="user-message">{{ value }}</p>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <p class="user-message user-created">{{ message }}</p>
    {% endif %}
    {% endfor %}
    {% endif %}


    <input type="submit" class="btn" value="{% trans 'Login' %}" id="login-btn">
    <div class="signup" id="signup-question">
        <p class="link-signup-question">{% trans "Don't have an account?" %}</p>
        <a class="link link-signup" href="{% url 'accounts:signup' %}">{% trans "Sign Up" %}</a>
    </div>
</form>

{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'accounts/js/login.js' %}"></script>
<script type="text/javascript">
    initializeLogin('{{ LANGUAGE_CODE }}');
</script>
{% endblock %}

langi/accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/layout.html' %}
{% load static %}
{% load sass_tags %}
{% load i18n %}

{% block title %}Password reset complete{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'accounts/css/forgotPassword.scss' %}">
{% endblock %}

{% block content %}

<h2>{% trans "Password reset complete." %}</h2>
<p>{% trans "Your new password has been set. You can log in now on the " %}<a class="link link-signup"
                href="{% url 'accounts:login' %}">{% trans "log in page" %}</a>.</p>

{% endblock %}

langi/accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/layout.html' %}
{% load static %}
{% load sass_tags %}
{% load i18n %}
{% load widget_tweaks %}
{% load accounts.accounts_tags %}

{% block title %}Enter new password{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'accounts/css/forgotPassword.scss' %}">
{% endblock %}

{% block content %}
{% get_current_language as LANGUAGE_CODE %}
{% if validlink %}
<h2>{% trans "Set a new password." %}</h2>

<form method="POST" action="" novalidate>
    {% csrf_token %}
    <div class="input-div pass">
        <div class="i">
            <i class="fas fa-lock"></i>
        </div>
        <div class="div">
            <h5>{% trans "New password" %}</h5>
            {% render_field form.new_password1 type="password" class="input" %}
        </div>
        <div class="info-div">
            <i class="fas fa-info-circle info-icon"></i>
            <div class="info-popup">
                {{ form.new_password1.help_text }}
            </div>
        </div>
    </div>
    <div class="input-div pass">
        <div class="i">
            <i class="fas fa-lock"></i>
        </div>
        <div class="div">
            <h5>{% trans "Confirm Password" %}</h5>
            {% render_field form.new_password2 type="password" class="input" %}
        </div>
    </div>

    <p class="user-message">{{ form|getMessage }}</p>


    <input type="submit" class="btn" value="{% trans 'Change my password' %}">
</form>
{% else %}
<p>{% trans "The password reset link was invalid, possibly because it has already been used. Please request a new
    password reset." %}
</p>
{% endif %}
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'accounts/js/resetConfirm.js' %}"></script>
<script type="text/javascript">
    initializeResetConfirm('{{ LANGUAGE_CODE }}');
</script>
{% endblock %}

langi/accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/layout.html' %}
{% load static %}
{% load sass_tags %}
{% load i18n %}

{% block title %}Check email{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'accounts/css/forgotPassword.scss' %}">
{% endblock %}

{% block content %}

<h2>{% trans "Check your inbox." %}</h2>
<p>{% trans "We've emailed you instructions for setting your password. You should receive the email shortly." %}</p>

{% endblock %}

langi/accounts/templates/accounts/password_reset_form.html
{% extends 'accounts/layout.html' %}
{% load static %}
{% load sass_tags %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}Forgot Your Password?{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'accounts/css/forgotPassword.scss' %}">
{% endblock %}

{% block content %}
{% get_current_language as LANGUAGE_CODE %}
<h2>{% trans "Forgot your password?" %}</h2>
<p>{% trans "Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form method="POST" action="{% url 'accounts:password_reset' %}" novalidate>
    {% csrf_token %}
    <div class="input-div email">
        <div class="i">
            <i class="fas fa-envelope"></i>
        </div>
        <div class="div">
            <h5>{% trans "Email" %}</h5>
            {% render_field form.email type="email" class="input" %}
        </div>
    </div>


    {% if form.errors %}
    {% for error_field, error_message in form.errors.items %}
    <p class="user-message">{{ error_message|striptags }}</p>
    {% endfor %}
    {% endif %}


    <input type="submit" class="btn" value="{% trans 'Send me instructions' %}">
</form>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'accounts/js/resetForm.js' %}"></script>
<script type="text/javascript">
    initializeResetForm('{{ LANGUAGE_CODE }}');
</script>
{% endblock %}

langi/accounts/templates/accounts/signup.html
{% extends 'accounts/layout.html' %}
{% load static %}
{% load sass_tags %}

{% load i18n %}
{% load widget_tweaks %}
{% load accounts.accounts_tags %}

{% block title %}SignUp{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'accounts/css/signup.scss' %}">
{% endblock %}


{% block content %}

{% get_current_language as LANGUAGE_CODE %}
{% get_language_info for LANGUAGE_CODE as lang %}

<form name="setLangEnglish" action="{% url 'set_language' %}" method="post" class="set-lang">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ redirect_to }}">
    <input type="hidden" name="language" value="en" id="lang-code" />
</form>

<form method="POST" action="{% url 'accounts:signup' %}" novalidate>
    {% csrf_token %}
    <div class="form__logo-panel logo-panel">
        <img class="logo-panel__full-logo" src="{% static 'accounts/images/FullLogo.png' %}" alt="Full Logo">
        <h1 class="logo-panel__title">{% trans "Create Account" %}</h1>
    </div>
    <div class="input-div uname">
        <div class="i">
            <i class="fas fa-user"></i>
        </div>
        <div class="div">
            <h5>{% trans "Username" %}</h5>
            {% render_field form.username type="text" class="input" %}
            <!--<input type="text" class="input">-->
        </div>
        <div class="info-div">
            <i class="fas fa-info-circle info-icon"></i>
            <div class="info-popup">
                {{ form.username.help_text }}
            </div>
        </div>
    </div>
    <div class="input-div email">
        <div class="i">
            <i class="fas fa-envelope"></i>
        </div>
        <div class="div">
            <h5>{% trans "Email" %}</h5>
            <!--<input type="email" class="input">-->
            {% render_field form.email type="email" class="input" %}
        </div>
    </div>
    <div class="input-div pass">
        <div class="i">
            <i class="fas fa-lock"></i>
        </div>
        <div class="div">
            <h5>{% trans "Password" %}</h5>
            <!--<input type="password" class="input">-->
            {% render_field form.password1 type="password" class="input" %}
        </div>
        <div class="info-div">
            <i class="fas fa-info-circle info-icon"></i>
            <div class="info-popup">
                {{ form.password1.help_text }}
            </div>
        </div>
    </div>
    <div class="input-div pass">
        <div class="i">
            <i class="fas fa-lock"></i>
        </div>
        <div class="div">
            <h5>{% trans "Confirm Password" %}</h5>
            <!--<input type="password" class="input">-->
            {% render_field form.password2 type="password" class="input" %}
        </div>
    </div>

    <div class="select-language">
        <div class="select-language__chose chose">
            <div class="open-list-btn">
                <a id="open-list" onclick="langSelected('{{ LANGUAGE_CODE }}')"><img
                        src="{% static 'accounts/images/LeftArrow.png' %}" id="arrow" onmouseover="hover()"
                        onmouseout="unhover()"></a>
            </div>
            <!--<input class="selected-language" value="{{ lang.name_local }}" id="selected-language-btn">
            {% render_field form.language type="text" class="selected-language" id="selected-language-btn" %}-->
            <input type="text" name="{{ form.language.name }}" class="selected-language" value="{{ lang.name_local }}"
                id="selected-language-btn" maxlength="{{ form.language.field.max_length }}"
                {% if form.language.field.required %}required{% endif %}>
            <ul id="list-languages" style="display: none">
                <li onclick="changeLanguage('de')" id="de" class='langfamily-ns'>
                    <p>Deutsch</p>
                </li>
                <li onclick="changeLanguage('cs')" id="cs" class='langfamily-ns'>
                    <p>Český</p>
                </li>
                <li onclick="changeLanguage('en')" id="en" class='langfamily-ns'>
                    <p>English</p>
                </li>
                <li onclick="changeLanguage('es')" id="es" class='langfamily-ns'>
                    <p>Español</p>
                </li>
                <li onclick="changeLanguage('fr')" id="fr" class='langfamily-ns'>
                    <p>Français</p>
                </li>
                <li onclick="changeLanguage('it')" id="it" class='langfamily-ns'>
                    <p>Italiano</p>
                </li>
                <li onclick="changeLanguage('lt')" id="lt" class='langfamily-ns'>
                    <p>Lietuviškai</p>
                </li>
                <li onclick="changeLanguage('nl')" id="nl" class='langfamily-ns'>
                    <p>Nederlands</p>
                </li>
                <li onclick="changeLanguage('pl')" id="pl" class='langfamily-ns'>
                    <p>Polski</p>
                </li>
                <li onclick="changeLanguage('pt')" id="pt" class='langfamily-ns'>
                    <p>Português</p>
                </li>
                <li onclick="changeLanguage('tr')" id="tr" class='langfamily-ns'>
                    <p>Türkçe</p>
                </li>
                <li onclick="changeLanguage('ru')" id="ru" class='langfamily-ns'>
                    <p>Русский</p>
                </li>
                <li onclick="changeLanguage('zh-tw')" id="zh-tw" class='langfamily-tc'>
                    <p>繁體中文</p>
                </li>
                <li onclick="changeLanguage('ja')" id="ja" class='langfamily-jp'>
                    <p>日本語</p>
                </li>
                <li onclick="changeLanguage('ko')" id="ko" class='langfamily-kr'>
                    <p>한국어</p>
                </li>
                <li onclick="changeLanguage('el')" id="el" class='langfamily-ns'>
                    <p>Ελληνικά</p>
                </li>
            </ul>
        </div>
    </div>
    <div class="checkbox-wrapper">
        <!--<input type="checkbox" id="check" hidden>-->
        <input type="checkbox" name="{{ form.agreement.name }}" id="check" hidden
            {% if form.agreement.field.required %}required{% endif %}>
        <label for="check" class="checkmark" id="checkLabel"></label>
        <div class="agreement-text" id="agreement">
            {% trans "I read and agree to " %}<a class="link"
                href="{% url 'accounts:terms' %}">{% trans "Terms &amp; Conditions" %}</a>
            <p class="second-line-agreement" id="second-line">{% trans " " %}</p>
        </div>
    </div>

    <p class="user-message">{{ form|getMessage }}</p>

    <input type="submit" class="btn" value="{% trans 'Sign Up' %}" id="signup-btn">
    <div class="signup">
        <p class="link-signup-question">{% trans "Already have an account?" %}</p>
        <a class="link link-signup" href="{% url 'accounts:login' %}">{% trans "Sign In" %}</a>
    </div>
</form>

{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'accounts/js/signup.js' %}"></script>
<script type="text/javascript">
    initializeSignUp('{{ LANGUAGE_CODE }}');
</script>
{% endblock %}