langi/langi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('api/', include('langiAPI.urls')),
    path('', include('accounts.urls')),
    path('', include('mainContent.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

langi/mainContent/urls.py
from django.urls import path

from . import views

app_name = 'mainContent'

urlpatterns = [
    path('', views.homePage, name='home'),
    path('decks/', views.deckPage, name='decks'),
    path('addCard/', views.addCardPage, name='addCard'),
    path('learn/', views.learnPage, name='learn'),
    path('games/', views.gamesPage, name='games'),
    path('about/', views.aboutPage, name='about'),
    path('ajax/change-language', views.changeLanguage, name='change-language'),
    path('ajax/change-theme', views.changeTheme, name='change-theme'),
    path('ajax/import-textFile', views.importTextFile, name='import-textFile'),
    path('ajax/import-imgFile', views.importImgFile, name='import-imgFile'),
]

langi/mainContent/models.py
from django.db import models

# Create your models here.

langi/mainContent/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

import cv2 as cv
import numpy as np

from docx import Document
from .functions import is_doc, to_image, to_data_uri
from .detectionMechanism import process, preprocess_edges, preprocess_checkered_paper


@login_required(login_url='accounts:login')
def homePage(request):
    return render(request, 'mainContent/home.html')


@login_required(login_url='accounts:login')
def deckPage(request):
    return render(request, 'mainContent/decks.html')


@login_required(login_url='accounts:login')
def addCardPage(request):
    return render(request, 'mainContent/addCard.html')


@login_required(login_url='accounts:login')
def learnPage(request):
    return render(request, 'mainContent/learn.html')


@login_required(login_url='accounts:login')
def gamesPage(request):
    return render(request, 'mainContent/games.html')


@login_required(login_url='accounts:login')
def aboutPage(request):
    return render(request, 'mainContent/about.html')


def changeLanguage(request):
    if request.is_ajax and request.method == "POST":
        language_code = request.POST.get("language", None)
        user = request.user
        user.profile.language = language_code
        user.save()
        return JsonResponse({'message': 'OK'}, status=200)
    return JsonResponse({"error": "Error during setting a new language!"}, status=400)


def changeTheme(request):
    if request.is_ajax and request.method == "POST":
        darkMode = request.POST.get("darkMode", None)
        if darkMode == 'true':
            darkMode = True
        else:
            darkMode = False
        user = request.user
        user.profile.darkMode = darkMode
        user.save()
        return JsonResponse({'message': 'OK'}, status=200)
    return JsonResponse({"error": ""}, status=400)


def importTextFile(request):
    if request.method == "POST":
        separator = request.POST.get("separator", None)
        textFile = request.FILES["file"]

        # get bytes of file
        rawdata = textFile.read()
        # read content from text file
        fileContent = []
        if is_doc(rawdata):
            # docx file -----------------------------------------------------------------------
            try:
                document = Document(textFile)
                for para in document.paragraphs:
                    s = para.text
                    if len(s) != 0 and s.isspace() is False:
                        fileContent.append(s)
            except Exception as ex:
                print(ex)
        else:
            # plain text file ----------------------------------------------------------------
            encoding = 'utf-8'
            try:
                for line in textFile:
                    s = line.decode(encoding=encoding)
                    if len(s) != 0 and s.isspace() is False:
                        fileContent.append(s)
            except Exception as ex:
                print(ex)

        # split lines by separator
        lines = []
        result = []
        for i in fileContent:
            if len(separator) != 0 and len(separator) < 2 and separator.isspace() is False:
                lines.append(i.split(separator))
            else:
                lines.append([i, ''])

        # create json with words
        for line in lines:
            if len(line) < 2 or len(line) > 2:
                result.append({"front": line[0], "back": ''})
            else:
                result.append({"front": line[0], "back": line[1]})

        # jsonResult = json.dumps(result, indent=1, ensure_ascii=False)
        return JsonResponse(result, safe=False, status=200)
    return JsonResponse({"error": ""}, status=400)


def importImgFile(request):
    if request.method == "POST":
        edges = request.POST.get("edges", None)
        checkered = request.POST.get("checkered", None)

        result = []

        imgFile = request.FILES["file"]

        nparr = np.frombuffer(imgFile.read(), np.uint8)
        img = cv.imdecode(nparr, cv.IMREAD_COLOR)

        if edges == "true":
            img = preprocess_edges(img)
       
        if checkered == "true":
            img = preprocess_checkered_paper(img)
       
        imgList = process(img)
      
        for imgTuple in imgList:
            tup = []
            for img in imgTuple:
                pil_image = to_image(img)
                image_uri = to_data_uri(pil_image)
                tup.append(image_uri)
            result.append(tup)
        return JsonResponse(result, safe=False, status=200)
    return JsonResponse({"error": ""}, status=400)

langi/mainContent/templates/mainContent/about.html
{% extends 'mainContent/layout.html' %}
{% load static %}
{% load sass_tags %}

{% load i18n %}
{% load widget_tweaks %}

{% block title %}About{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'mainContent/css/slick.scss' %}">
<link rel="stylesheet" type="text/css" href="{% sass_src 'mainContent/css/home.scss' %}">
<link rel="stylesheet" type="text/css" href="{% sass_src 'mainContent/css/slickHandle.scss' %}">
<link rel="stylesheet" type="text/css" href="{% sass_src 'mainContent/css/about.scss' %}">
{% endblock %}

{% block content %}
{% get_current_language as LANGUAGE_CODE %}

{% include 'mainContent/tiles.html' %}

<div class="decks-container">
    <div class="about-content">
        <h1>{% trans "Welcome to the LANGI Application" %}</h1>
        <p>{% trans "Last updated: June 28, 2020" %}</p><br><br>
        <p class="about-main-text">{% blocktrans %}
            The langi web application was created for all users who wish to develop their language skills in a pleasant
            and convenient way. The application allows you to view and learn the cards you have created using one of the
            most popular
            SRS (Spaced Repetition System) algorithms, SM-2. In addition, apart from the classic approach that
            allows you to add new flashcards, the user also has the option of automatically creating word sets from the
            imported files. The application supports both text document files as well as image files such as .png or
            .jpg. The presence of mini-games, with the help of which the user can learn new words or expressions, also
            contributes to pleasant learning. For the convenience of the user, the application supports 16 interface
            languages ​​and two color modes. The "light" mode, which is the default mode, and the "dark" mode, which,
            due to a number of tests, will certainly be better suited for night use of the application.
            {% endblocktrans %}
        </p><br>
        <p class="about-main-text">{% blocktrans %}
            The application was created with the use of Django technology and Django REST framework, as well as with the
            help of the OpenCV (Open Source Computer Vision) library.
            {% endblocktrans %}</p><br>
    </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'mainContent/js/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'mainContent/js/slickHandle.js' %}"></script>
{% endblock %}

langi/mainContent/templates/mainContent/activity.html
{% load i18n %}
{% load static %}

<div class="activity-window" id="activity-window">
    <div class="add-header activity-header">
        <div class="add-header-top activity-header-top">
            <div class="title">{% trans "Activity" %}</div>
            <button data-activity-close class="close-btn">&times;</button>
        </div>
    </div>
    <div class="body-and-select-container">
        <div class="activity-deck-selection-content">
            <div class="deck-selection">
                {% include 'mainContent/selectDeckList.html' %}
            </div>
        </div>
        <div class="activity-body">
            <div id="today-activity-content" class="activity-content">
                <div class="activity-text">
                    {% trans 'All' %}
                </div>
                <canvas id="today-dif-chart"></canvas>
                <canvas id="today-games-chart"></canvas>
            </div>
            <div id="activity-words-content" class="activity-words-content"></div>
        </div>
    </div>
</div>

langi/mainContent/templates/mainContent/addDeck.html
{% load static %}
{% load sass_tags %}

{% load i18n %}
{% load widget_tweaks %}

<div class="add-deck-window" id="add-deck-window">
    <div class="add-header add-deck-header">
        <div class="add-header-top add-card-header-top">
            <div class="title">{% trans 'Create New Deck' %}</div>
            <button data-adddeck-close class="close-btn">&times;</button>
        </div>
    </div>
    <div class="add-deck-body">
        <div class="input-div deckname">
            <div class="div">
                <h5>{% trans "Name" %}</h5>
                <input id="deckNameInputId" type="text" class="input" maxlength="100">
            </div>
        </div>
        <div class="input-div decktags">
            <div class="div">
                <h5>{% trans "Maximum 5 tags separated by commas" %}</h5>
                <input id="deckTagsInputId" type="text" class="input" maxlength="150">
            </div>
        </div>

        <div class="required-error required-hide">
            <span>{% trans "The Name field is required." %}</span>
        </div>
    </div>
    <div class="add-cancel">
        <div class="addDeck-btn-div create-add" id="createDeck">
            <button type="submit" class="btn">{% trans "Add" %}</button>
        </div>
        <div class="cancelDeck-btn-div create-add">
            <button class="btn">{% trans "Cancel" %}</button>
        </div>
    </div>
</div>

langi/mainContent/templates/mainContent/deckSettings.html
{% load static %}
{% load sass_tags %}

{% load i18n %}
{% load widget_tweaks %}

<div class="deck-settings-window" id="deck-settings-window">
    <div class="add-header deck-settings-header">
        <div class="add-header-top deck-settings-header-top">
            <div class="title">{% trans 'Deck Settings' %}</div>
            <button data-decksettings-close class="close-btn">&times;</button>
        </div>
        <span class="deck-settings-deck-name">Testowa nazwa talii</span>
    </div>
    <div class="deck-settings-body">
        <div class="deck-set-headings">
            <div class="deck-set-title">
                <p>{% trans 'Delete' %}</p>
            </div>
            <div class="deck-set-title">
                <p>{% trans 'Rename' %}</p>
            </div>
            <div class="deck-set-title">
                <p>{% trans 'Change Tag' %}</p>
            </div>
            <div class="deck-set-title">
                <p>{% trans 'Import from text file' %}</p>
            </div>
            <div class="deck-set-title">
                <p>{% trans 'Import from image file' %}</p>
            </div>
        </div>
        <div class="deck-set-line"></div>
        <div class="deck-set-contents">
            <div class="deck-set-content">
                <p class="deck-set-content-title">{% trans 'Delete Deck' %}</p>
                <p class="deck-set-content-text">
                    {% trans 'Warning! Deck will be removed along with all its flashcards.' %}</p>
                <div class="deck-set-delete create-add">
                    <button type="submit" class="btn deck-set-btn"
                        id="deck-set-delete-deck">{% trans "Delete" %}</button>
                </div>
            </div>
            <div class="deck-set-content">
                <p class="deck-set-content-title">{% trans 'Rename Deck' %}</p>
                <p class="deck-set-content-text">
                    {% trans 'Enter new name for this deck and click CHANGE.' %}</p>
                <div class="input-div">
                    <div class="div">
                        <h5>{% trans "Enter new name for this deck" %}</h5>
                        <input type="text" class="input deck-settings-change-name">
                    </div>
                </div>
                <div class="required-name-error required-name-hide">
                    <span>{% trans "The Name field is required." %}</span>
                </div>
                <div class="deck-set-change create-add">
                    <button type="submit" class="btn deck-set-btn"
                        id="deck-set-change-name">{% trans "Change" %}</button>
                </div>
            </div>
            <div class="deck-set-content">
                <p class="deck-set-content-title">{% trans "Change Deck's tags" %}</p>
                <p class="deck-set-content-text">
                    {% trans 'Enter new tags for this deck. Maximum 5 tags separated by commas.' %}</p>
                <div class="input-div">
                    <div class="div">
                        <h5>{% trans "Maximum 5 tags separated by commas" %}</h5>
                        <input type="text" class="input deck-settings-change-tags">
                    </div>
                </div>
                <div class="deck-set-change create-add">
                    <button type="submit" class="btn deck-set-btn"
                        id="deck-set-change-tags">{% trans "Change" %}</button>
                </div>
            </div>
            {% include 'mainContent/importTextFiles.html' %}
        </div>
    </div>
</div>

langi/mainContent/templates/mainContent/dictionary.html
{% load i18n %}
{% load static %}

<div class="dictionary-window" id="dictionary-window">
    <div class="add-header dictionary-header">
        <div class="add-header-top dictionary-header-top">
            <div class="title">{% trans "Dictionary" %}</div>
            <button data-dict-close class="close-btn">&times;</button>
        </div>
    </div>
    <div class="body-and-select-container">
        <div class="dict-deck-selection-content">
            <div class="deck-selection">
                {% include 'mainContent/selectDeckList.html' %}
            </div>
        </div>
        <div class="dictionary-body">
            <div id="dict-content" class="dict-content"></div>
        </div>
    </div>
</div>

langi/mainContent/templates/mainContent/home.html
{% extends 'mainContent/layout.html' %}
{% load static %}
{% load sass_tags %}

{% load i18n %}
{% load widget_tweaks %}

{% block title %}Home{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'mainContent/css/home.scss' %}">
{% endblock %}

{% block content %}
{% get_current_language as LANGUAGE_CODE %}

{% include 'mainContent/tiles.html' %}

{% endblock %}

langi/mainContent/templates/mainContent/importFiles.html
{% load i18n %}
{% load static %}

<div class="import-files-window" id="import-files-window">
    <div class="add-header import-files-header">
        <div class="add-header-top import-files-header-top">
            <div class="title">{% trans "Import Files" %}</div>
            <button data-import-files-close class="close-btn">&times;</button>
        </div>
    </div>
    <div class="body-and-select-container">
        <div class="import-deck-selection-content">
            <div class="import-no-deck-error" id="import-no-deck-error">
                {% trans 'You should choose any deck.' %}</div>
            <div class="deck-selection">
                {% include 'mainContent/selectDeckList.html' %}
            </div>
        </div>
        <div class="import-files-body">
            <div class="import-files-headings">
                <div class="import-files-title">
                    <p>{% trans 'Import from text file' %}</p>
                </div>
                <div class="import-files-title">
                    <p>{% trans 'Import from image file' %}</p>
                </div>
            </div>
            <div class="import-files-line"></div>
            <div class="import-files-contents">
                {% include 'mainContent/importTextFiles.html' %}
            </div>
        </div>
    </div>
</div>

langi/mainContent/templates/mainContent/importTextFiles.html
{% load i18n %}
{% load static %}

<div class="deck-set-content">
    <p class="deck-set-content-title">{% trans "Import from text file" %}</p>
    <p class="deck-set-content-text">
        {% trans 'Add text file into box field located underneath. Accepted file formats are .txt, .docx. In the field on the right side enter a proper flashcard separator.' %}
    </p>
    <div class="drop-file-zone-container">
        <div class="drop-file-zone">
            <span class="drop-file-zone__prompt">{% trans 'Drop file here or click to upload' %}</span>
            <!--<span class="drop-file-zone__error">{% trans 'Invalid file format' %}</span>-->
            <!--<div class="drop-file-zone__thumb" data-img-label="myImg.png"></div>-->
            <input type="file" name="textFile" class="drop-file-zone__input">
        </div>
        <div class="input-div">
            <div class="div">
                <h5>{% trans 'Separator' %}</h5>
                <input id="separator" type="text" class="input">
            </div>
        </div>
    </div>
    <div class="deck-set-change create-add">
        <button id="importTxtFileBtn" class="btn deck-set-btn" onclick="importTextFile()"
            import-textfile-url="{% url 'mainContent:import-textFile' %}">{% trans "Import" %}</button>
    </div>
    <div class="deck-set-im-list-container">
        <div class="dect-set-im-header">
            <div class="deck-set-im-header-front">{% trans "Front" %}</div>
            <svg id="swap-img" class="swap-img" x="0px" y="0px" viewBox="0 0 384 384"
                style="enable-background:new 0 0 384 384;">
                <g>
                    <polygon
                        points="85.12,170.667 0,256 85.12,341.333 85.12,277.333 234.667,277.333 234.667,234.667 85.12,234.667 			" />
                    <polygon
                        points="384,128 298.88,42.667 298.88,106.667 149.333,106.667 149.333,149.333 298.88,149.333 298.88,213.333 			" />
                </g>
            </svg>
            <div class="deck-set-im-header-front">{% trans "Back" %}</div>
        </div>
        <div id="dect-set-im-list-elements-container" class="dect-set-im-list-elements-container">
        </div>
    </div>
    <div class="deck-set-save deck-set-change create-add">
        <button type="submit" id="deck-set-save-btn"
            class="deck-set-save-btn btn deck-set-btn">{% trans "Save" %}</button>
    </div>
</div>
<div class="deck-set-content">
    <p class="deck-set-content-title">{% trans "Import from image file" %}</p>
    <p class="deck-set-content-text">
        {% trans 'Add image file into box field located underneath. Accepted file formats are .png, .jpg, .jpeg. Mark proper checkboxes for better extraction result.' %}
    </p>
    <div class="drop-file-img-zone-container">
        <div class="drop-file-img-zone">
            <span class="drop-file-img-zone__prompt">{% trans 'Drop file here or click to upload' %}</span>
            <!--<span class="drop-file-img-zone__error">{% trans 'Invalid file format' %}</span>-->
            <!--<div class="drop-file-img-zone__thumb" data-img-label="myImg.png"></div>-->
            <input type="file" name="textFile" class="drop-file-img-zone__input">
        </div>

        <div class="checkboxes">
            <div class="checkbox-wrapper">
                <!--<input type="checkbox" id="paper-edges-checkbox" hidden>-->
                <input type="checkbox" name="paperEdgesCheckbox" id="paper-edges-checkbox" hidden>
                <label for="paper-edges-checkbox" class="checkmark" id="paper-edges-label"></label>
                <span class="checkbox-text">{% trans "The photo shows all corners of the paper." %}</span>
            </div>

            <div class="checkbox-wrapper">
                <!--<input type="checkbox" id="paper-checkered" hidden>-->
                <input type="checkbox" name="paperCheckered" id="paper-checkered" hidden>
                <label for="paper-checkered" class="checkmark" id="paper-checkered-label"></label>
                <span class="checkbox-text">{% trans "The checkered paper was used." %}</span>
            </div>
        </div>
    </div>
    <div class="deck-set-change create-add">
        <button id="importImgFileBtn" class="btn deck-set-btn" onclick="importImageFile()"
            import-imgfile-url="{% url 'mainContent:import-imgFile' %}">{% trans "Import" %}</button>
    </div>
    <div class="deck-set-im-list-container">
        <div class="dect-set-im-header">
            <div class="deck-set-im-header-front">{% trans "Front" %}</div>
            <svg id="swap-image-img" class="swap-img" x="0px" y="0px" viewBox="0 0 384 384"
                style="enable-background:new 0 0 384 384;">
                <g>
                    <polygon
                        points="85.12,170.667 0,256 85.12,341.333 85.12,277.333 234.667,277.333 234.667,234.667 85.12,234.667 			" />
                    <polygon
                        points="384,128 298.88,42.667 298.88,106.667 149.333,106.667 149.333,149.333 298.88,149.333 298.88,213.333 			" />
                </g>
            </svg>
            <div class="deck-set-im-header-front">{% trans "Back" %}</div>
        </div>
        <div id="dect-set-image-list-elements-container" class="dect-set-im-list-elements-container">
        </div>
    </div>
    <div class="deck-set-save deck-set-change create-add">
        <button type="submit" id="deck-set-image-save-btn"
            class="deck-set-save-btn btn deck-set-btn">{% trans "Save" %}</button>
    </div>
</div>

langi/mainContent/templates/mainContent/tiles.html
{% load i18n %}
{% load static %}
<section class="tiles" id="tiles">
    <a href="{% url 'mainContent:decks' %}">
        <div class="tile decksOrangeTransparent" onmouseover="IconHover(this);" onmouseout="IconUnhover(this);">
            <img src="{% static 'mainContent/images/icons/decksTransparent.png' %}" alt="">
            <div class="line"></div>
            <p class="tile__title">{% trans 'Decks' %}</p>
        </div>
    </a>


    <a role="button" data-addcard-open="#add-card-window">
        <div class="tile addCardOrangeTransparent" onmouseover="IconHover(this);" onmouseout="IconUnhover(this);">
            <img src="{% static 'mainContent/images/icons/addCardTransparent.png' %}" alt="">
            <div class="line"></div>
            <p class="tile__title">{% trans 'Add Card' %}</p>
        </div>
    </a>


    <a href="{% url 'mainContent:learn' %}">
        <div class="tile learnOrangeTransparent" onmouseover="IconHover(this);" onmouseout="IconUnhover(this);">
            <img src="{% static 'mainContent/images/icons/learnTransparent.png' %}" alt="">
            <div class="line"></div>
            <p class="tile__title">{% trans 'Learn' %}</p>
        </div>
    </a>

    <a role="button" data-dict-open="#dictionary-window">
        <div class="tile dictionaryOrangeTransparent" onmouseover="IconHover(this);" onmouseout="IconUnhover(this);">
            <img src="{% static 'mainContent/images/icons/dictionaryTransparent.png' %}" alt="">
            <div class="line"></div>
            <p class="tile__title">{% trans 'Dictionary' %}</p>
        </div>
    </a>

    <a href="{% url 'mainContent:games' %}">
        <div class="tile gamesOrangeTransparent" onmouseover="IconHover(this);" onmouseout="IconUnhover(this);">
            <img src="{% static 'mainContent/images/icons/gamesTransparent.png' %}" alt="">
            <div class="line"></div>
            <p class="tile__title">{% trans 'Games' %}</p>
        </div>
    </a>


    <a role="button" data-activity-open="#activity-window">
        <div class="tile activityOrangeTransparent" onmouseover="IconHover(this);" onmouseout="IconUnhover(this);">
            <img src="{% static 'mainContent/images/icons/activityTransparent.png' %}" alt="">
            <div class="line"></div>
            <p class="tile__title">{% trans 'Activity' %}</p>
        </div>
    </a>


    <a role="button" data-import-files-open="#import-files-window">
        <div class="tile importOrangeTransparent" onmouseover="IconHover(this);" onmouseout="IconUnhover(this);">
            <img src="{% static 'mainContent/images/icons/importTransparent.png' %}" alt="">
            <div class="line"></div>
            <p class="tile__title">{% trans 'Import' %}</p>
        </div>
    </a>



</section>